version "3.5"

networks:
        localhost

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/vmaricru/data/wordpress
                        o: bind
                        type: none

        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/vmaricru/data/mariadb
                        o: bind
                        type: none
